package rules
import Device;
import Calcutils;

dialect "mvel"

rule "Make apple discount for new model"
    when
    device: Device(brand == "Apple")
    user: Customer(hasApple(),
                    hasOldToNewDiscount(device), money > 0)
    then
    System.out.println("You can change your old Apple device on New device with 30% discount");
end

rule "Make apple discount for same model"
    when
    device: Device(brand == "Apple")
    user: Customer(hasApple(),
                    !hasOldToNewDiscount(device), money > 0)
    then
    System.out.println("You can change your old Apple device on New device with 50% discount");
end

rule "Make device discount"
    when
    util: Calcutils()
    device: Device(brand == "Apple")
    user: Customer(!hasApple(), util.makeDiscountIfOldDeviceExpensive(curDevice, device), money > 0)
    then
    System.out.println("You can change your another brand on Iphone with 30%")
end

rule "Don't device discount"
    when
    util: Calcutils()
    device: Device(brand == "Apple")
    user: Customer(!hasApple(), !util.makeDiscountIfOldDeviceExpensive(curDevice, device), money > 0)
    then
    System.out.println("You can't change your another brand on Iphone")
end